### ISSUE TITLE
TTS was broken, and the program could not be compiled to exe.

### ISSUE THREAD

**Issue by DBright682** [ashfaaqrifath/SCP-Foundation-Terminal#2]
I have fixed all of the obvious issues, such as TTS cutting out after the first paragraph, and the script being impossible to compile to exe in one file mode.

Now anyone with a windows PC (or software that adds a windows executable compatibility layer) can enjoy the program without having to install python!

**Comment by ashfaaqrifath** [comment]
Can u give me a list of the issues that you found, it wud be helpful for next time. 
And I've tried converting this to an exe but the TTS does not allow it, not only in this project but also in other projects I've used TTS in. Maybe it's an issue with the pyttsx3 package, I can't quite find the problem. Feel free to suggest any features I can add to this project, always wanted to collaborate with someone on this.👍
